logistics
../domains/Logistics/Track1/Typed/
domain.pddl
probLOGISTICS-4-0.pddl
probLOGISTICS-4-0.pddl
probLOGISTICS-4-1.pddl
probLOGISTICS-4-2.pddl
probLOGISTICS-5-0.pddl
probLOGISTICS-5-1.pddl
probLOGISTICS-5-2.pddl
probLOGISTICS-6-0.pddl
probLOGISTICS-6-1.pddl
probLOGISTICS-6-2.pddl
probLOGISTICS-6-3.pddl
probLOGISTICS-7-0.pddl
probLOGISTICS-7-1.pddl
probLOGISTICS-8-0.pddl
probLOGISTICS-8-1.pddl
probLOGISTICS-9-0.pddl
probLOGISTICS-9-1.pddl
probLOGISTICS-10-0.pddl
probLOGISTICS-10-1.pddl
probLOGISTICS-11-0.pddl
probLOGISTICS-11-1.pddl
probLOGISTICS-12-0.pddl
probLOGISTICS-12-1.pddl
probLOGISTICS-13-0.pddl
probLOGISTICS-13-1.pddl
probLOGISTICS-14-0.pddl
probLOGISTICS-14-1.pddl
probLOGISTICS-15-0.pddl
probLOGISTICS-15-1.pddl
Additional/problogistics-16-0.pddl
Additional/problogistics-16-1.pddl
Additional/problogistics-17-0.pddl
Additional/problogistics-17-1.pddl
Additional/problogistics-18-0.pddl
Additional/problogistics-18-1.pddl
Additional/problogistics-19-0.pddl
Additional/problogistics-19-1.pddl
Additional/problogistics-20-0.pddl
Additional/problogistics-20-1.pddl
Additional/problogistics-21-0.pddl
Additional/problogistics-21-1.pddl
Additional/problogistics-22-0.pddl
Additional/problogistics-22-1.pddl
Additional/problogistics-23-0.pddl
Additional/problogistics-23-1.pddl
Additional/problogistics-24-0.pddl
Additional/problogistics-24-1.pddl
Additional/problogistics-25-0.pddl
Additional/problogistics-25-1.pddl
Additional/problogistics-26-0.pddl
Additional/problogistics-26-1.pddl
Additional/problogistics-27-0.pddl
Additional/problogistics-27-1.pddl
Additional/problogistics-28-0.pddl
Additional/problogistics-28-1.pddl
Additional/problogistics-29-0.pddl
Additional/problogistics-29-1.pddl
Additional/problogistics-30-0.pddl
Additional/problogistics-30-1.pddl
Additional/problogistics-31-0.pddl
Additional/problogistics-31-1.pddl
Additional/problogistics-32-0.pddl
Additional/problogistics-32-1.pddl
Additional/problogistics-33-0.pddl
Additional/problogistics-33-1.pddl
Additional/problogistics-34-0.pddl
Additional/problogistics-34-1.pddl
Additional/problogistics-35-0.pddl
Additional/problogistics-35-1.pddl
Additional/problogistics-36-0.pddl
Additional/problogistics-36-1.pddl
Additional/problogistics-37-0.pddl
Additional/problogistics-37-1.pddl
Additional/problogistics-38-0.pddl
Additional/problogistics-38-1.pddl
Additional/problogistics-39-0.pddl
Additional/problogistics-39-1.pddl
Additional/problogistics-40-0.pddl
Additional/problogistics-40-1.pddl
Additional/problogistics-41-0.pddl
Additional/problogistics-41-1.pddl
