 python assemble.py -i blocks -p ../JSHOP2/htndescs/blocks
 python assemble.py -i depots -p ../JSHOP2/htndescs/depots
 python assemble.py -i driverlog -p ../JSHOP2/htndescs/driverlog
 python assemble.py -i elevator -p ../JSHOP2/htndescs/elevator
 python assemble.py -i freecell -p ../JSHOP2/htndescs/freecell
 python assemble.py -i logistics -p ../JSHOP2/htndescs/logistics
 python assemble.py -i rovers -p ../JSHOP2/htndescs/rovers
 python assemble.py -i satellite -p ../JSHOP2/htndescs/satellite
 python assemble.py -i zenotravel -p ../JSHOP2/htndescs/zenotravel