 python3 assemble.py -i blocks -o ../JSHOP2/htndescs/blocks
 python3 assemble.py -i depots -o ../JSHOP2/htndescs/depots
 python3 assemble.py -i driverlog -o ../JSHOP2/htndescs/driverlog
 python3 assemble.py -i elevator -o ../JSHOP2/htndescs/elevator
 python3 assemble.py -i freecell -o ../JSHOP2/htndescs/freecell
 python3 assemble.py -i logistics -o ../JSHOP2/htndescs/logistics
 python3 assemble.py -i rovers -o ../JSHOP2/htndescs/rovers
 python3 assemble.py -i satellite -o ../JSHOP2/htndescs/satellite
 python3 assemble.py -i zenotravel -o ../JSHOP2/htndescs/zenotravel